### ISSUE TITLE
Curly brackets seem to mess with syntax highlight

### ISSUE THREAD

**Issue by Gankarloo** [yko/mojo.vim#10]
Syntax highlight is working fine util I enter a line like this.
`% for $line (@$rows) {`

It looks good until I insert the opening curly bracket, everything after is strangely highlighted.

With Curly bracket.
![2015-05-20 13_55_33-11744 _work_webapps_mojo-webapp](https://cloud.githubusercontent.com/assets/12395912/7725120/f8480c26-fef7-11e4-995e-71382a838f37.png)

Without Curly bracket.
![2015-05-20 13_56_59-11744 _work_webapps_mojo-webapp](https://cloud.githubusercontent.com/assets/12395912/7725157/38ea34fc-fef8-11e4-8ee2-f3280c3dd643.png)

**Comment by PerlPong** [comment]
I have the same issue, after upgrading from vim 7.3 to vim 7.4.

**Comment by yko** [comment]
This should be fixed by the merge of PR #11. Please reopen if it's still a problem.
Thanks!
