### ISSUE TITLE
inside perl block, html is highlighted as perl

### ISSUE THREAD

**Issue by vitstradal** [yko/mojo.vim#8]
As mentioned in #7 by rshadow:

```
% if(1) {
       <tr class="<%= join ' ', @class %>" >
              <td>  
% }
```

Html code between `{}` is highlited as it was perl.
To me it looks like in epl.vim

```
syn region PerlInside keepend start=+^\s*%=\{0,2}+hs=s end=+$+ contains=MojoSingleStart,@Perl
```

the `keepend` is ignored. Maybe error in vim?

**Comment by yko** [comment]
This should be fixed by the merge of PR #11. Please reopen if it's still a problem.
Thanks!
