### ISSUE TITLE
__DATA__ not highlighted

### ISSUE THREAD

**Issue by MortalCatalyst** [yko/mojo.vim#9]
I have put these lines in my .vimrc

let mojo_highlight_data = 1
let mojo_disable_html = 1

When I load vim with file hello with file contents like this, the section below **DATA** isn't highlighted.
# !/usr/bin/env perl

use Mojolicious::Lite;

get '/:fname/:lname' => sub {
    shift->render('hello');
};

app->start; 

**DATA**

@@ hello.html.ep
<!doctype html><html>
    <head><title>Placeholders</title></head>
    <body><i>Hello <%= $fname %> <%= $lname %></li></body>
</html>

**Comment by yko** [comment]
I assume this has been resolved a while ago with vim-perl/vim-perl@7dc74fe.
Closing now, please reopen if still valid.

Thanks!
